// root layout (RootLayout.js)
import { Geist, Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Header from "@/components/Header";
import { AnimatePresence, motion } from "framer-motion";
import PageWrapper from "@/components/PageWrapper";
import ConditionalNavigation from "@/components/ConditionalNavigation";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Note App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <PageWrapper>{children}</PageWrapper>
        <ConditionalNavigation />
      </body>
    </html>
  );
}
